[phases.setup]
nixPkgs = ["python3_13"]

[phases.install]
cmds = ["pip install -r requirements-web.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

